export const ASSET_CATEGORIES = {
    FOREX: [
        "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "USDCHF", "NZDUSD",
        "EURGBP", "EURJPY", "GBPJPY", "AUDJPY", "CADJPY", "CHFJPY", "NZDJPY",
        "EURAUD", "EURNZD", "GBPAUD", "GBPNZD", "AUDNZD", "AUDCAD", "NZDCAD"
    ],
    CRYPTO: [
        "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT",
        "DOGEUSDT", "AVAXUSDT", "DOTUSDT", "MATICUSDT", "LINKUSDT", "UNIUSDT",
        "LTCUSDT", "ATOMUSDT", "NEARUSDT", "APTUSDT", "XLMUSDT", "HBARUSDT"
    ],
    INDICES: [
        "OANDA:SPX500USD", "OANDA:NAS100USD", "OANDA:US30USD", "TVC:DEU40", "TVC:UK100",
        "TVC:EU50", "TVC:FR40", "TVC:JP225", "TVC:AU200", "TVC:HK33"
    ],
    METALS: [
        "OANDA:XAUUSD", "OANDA:XAGUSD", "TVC:PLATINUM", "TVC:PALLADIUM", "TVC:USOIL", "TVC:UKOIL"
    ],
    STOCKS: [
        "NASDAQ:AAPL", "NASDAQ:TSLA", "NASDAQ:NVDA", "NASDAQ:MSFT", "NASDAQ:AMZN",
        "NASDAQ:GOOGL", "NASDAQ:META", "NASDAQ:NFLX", "NASDAQ:AMD", "NASDAQ:INTC",
        "NYSE:BABA", "NYSE:JPM", "NYSE:V", "NYSE:WMT", "NYSE:DIS"
    ]
}

export type AssetCategory = keyof typeof ASSET_CATEGORIES
