export const timezones = [
    { value: 'Etc/UTC', label: '(UTC) UTC' },
    { value: 'America/New_York', label: '(UTC-5) New York' },
    { value: 'America/Chicago', label: '(UTC-6) Chicago' },
    { value: 'America/Denver', label: '(UTC-7) Denver' },
    { value: 'America/Los_Angeles', label: '(UTC-8) Los Angeles' },
    { value: 'America/Phoenix', label: '(UTC-7) Phoenix' },
    { value: 'America/Toronto', label: '(UTC-5) Toronto' },
    { value: 'America/Vancouver', label: '(UTC-8) Vancouver' },
    { value: 'America/Sao_Paulo', label: '(UTC-3) Sao Paulo' },
    { value: 'Europe/London', label: '(UTC+0) London' },
    { value: 'Europe/Paris', label: '(UTC+1) Paris' },
    { value: 'Europe/Berlin', label: '(UTC+1) Berlin' },
    { value: 'Europe/Moscow', label: '(UTC+3) Moscow' },
    { value: 'Asia/Dubai', label: '(UTC+4) Dubai' },
    { value: 'Asia/Kolkata', label: '(UTC+5:30) Kolkata' },
    { value: 'Asia/Bangkok', label: '(UTC+7) Bangkok' },
    { value: 'Asia/Singapore', label: '(UTC+8) Singapore' },
    { value: 'Asia/Shanghai', label: '(UTC+8) Shanghai' },
    { value: 'Asia/Tokyo', label: '(UTC+9) Tokyo' },
    { value: 'Australia/Sydney', label: '(UTC+10) Sydney' },
    { value: 'Pacific/Auckland', label: '(UTC+12) Auckland' },
]
